def getAge(ageID):
    if int(ageID) in [1,2,3]:
        return '0'
    if int(ageID) in [103,104]:
        return 'NULL' 
    return str((int(ageID) - 3))


sex_code = {
    'M':'Male',
    'F':'Female',
    'U':'Unknown',
    'X':'Not Specified'
}

ethnicity_id = {
    '10':'Hispanic or Latino',
    '20':'Not Hispanic or Latino',
    '30':'Multiple',
    '40':'Unknown',
    '50':'Not Specified'
}

race_id = {
    '98':'Unknown',
    '10':'White',
    '20':'Black or African American',
    '30':'American Indian or Alaska Native',
    '40':'Asian',
    '41':'Asian, Native Hawaiian or other Pacific Islander',
    '42':'Chinese',
    '43':'Japanese',
    '50':'Native Hawaiian or Other Pacific Islander',
    '60':'Other',
    '70':'Multiple',
    '99':'Not Specified'
}

relationship_id = {
    '1' :'Victim Was Acquaintance',
    '2' :'Victim Was Babysittee',
    '3' :'Victim Was Boyfriend/Girlfriend',
    '4' :'Victim Was Child of Boyfriend or Girlfriend',
    '5' :'Victim Was Child',
    '6' :'Victim Was Common-Law Spouse',
    '7' :'Victim was Employee',
    '8' :'Victim was Employer',
    '9' :'Victim Was Friend',
    '10':'Victim Was Grandchild',
    '11':'Victim Was Grandparent',
    '12':'Homosexual Relationship',
    '13':'Victim Was In-law',
    '14':'Victim Was Neighbor',
    '15':'Victim Was Other Family Member',
    '16':'Victim was Otherwise Known',
    '17':'Victim Was Parent',
    '18':'Relationship Unknown',
    '19':'Victim Was Sibling',
    '20':'Victim Was Stepchild',
    '21':'Victim Was Spouse',
    '22':'Victim Was Stepparent',
    '23':'Victim Was Stepsibling',
    '24':'Victim Was Stranger',
    '25':'Victim Was Offender',
    '26':'Victim was Ex-Spouse',
    '27':'Victim Was Ex-Relationship (Ex-Boyfriend/Girlfriend)',
    '28':'Cohabitant (non-intimate relationship)',
    '29':'Victim was Foster Parent',
    '30':'Victim was Foster Child'
}

relationship_code = {
    'AQ':'Victim Was Acquaintance',
    'BE':'Victim Was Babysittee',
    'BG':'Victim Was Boyfriend/Girlfriend',
    'CF':'Victim Was Child of Boyfriend or Girlfriend',
    'CH':'Victim Was Child',
    'CS':'Victim Was Common-Law Spouse',
    'EE':'Victim was Employee',
    'ER':'Victim was Employer',
    'FR':'Victim Was Friend',
    'GC':'Victim Was Grandchild',
    'GP':'Victim Was Grandparent',
    'HR':'Homosexual Relationship',
    'IL':'Victim Was In-law',
    'NE':'Victim Was Neighbor',
    'OF':'Victim Was Other Family Member',
    'OK':'Victim was Otherwise Known',
    'PA':'Victim Was Parent',
    'RU':'Relationship Unknown',
    'SB':'Victim Was Sibling',
    'SC':'Victim Was Stepchild',
    'SE':'Victim Was Spouse',
    'SP':'Victim Was Stepparent',
    'SS':'Victim Was Stepsibling',
    'ST':'Victim Was Stranger',
    'VO':'Victim Was Offender',
    'XS':'Victim was Ex-Spouse',
    'XR':'Victim Was Ex-Relationship (Ex-Boyfriend/Girlfriend)',
    'CO':'Cohabitant (non-intimate relationship)',
    'FP':'Victim was Foster Parent',
    'FC':'Victim was Foster Child'
}

location_id = {
    '1':'Abandoned/Condemned Structure',
    '2':'Air/Bus/Train Terminal',
    '3':'Amusement Park',
    '4':'Arena/Stadium/Fairgrounds/Coliseum',
    '5':'ATM Separate from Bank',
    '6':'Auto Dealership New/Used',
    '7':'Bank/Savings and Loan',
    '8':'Bar/Nightclub',
    '9':'Camp/Campground',
    '10':'Church/Synagogue/Temple/Mosque',
    '11':'Commercial/Office Building',
    '12':'Community Center',
    '13':'Construction Site',
    '14':'Convenience Store',
    '15':'Cyberspace',
    '16':'Daycare Facility',
    '17':'Department/Discount Store',
    '18':'Dock/Wharf/Freight/Modal Terminal',
    '19':"Drug Store/Doctors Office/Hospital",
    '20':'Farm Facility',
    '21':'Field/Woods',
    '22':'Gambling Facility/Casino/Race Track',
    '23':'Government/Public Building',
    '24':'Grocery/Supermarket',
    '25':'Highway/Road/Alley/Street/Sidewalk',
    '26':'Hotel/Motel/Etc.',
    '27':'Industrial Site',
    '28':'Jail/Prison/Penitentiary/Corrections Facility',
    '29':'Lake/Waterway/Beach',
    '30':'Liquor Store',
    '31':'Military Installation',
    '32':'Park/Playground',
    '33':'Parking/Drop Lot/Garage',
    '34':'Rental Storage Facility',
    '35':'Residence/Home',
    '36':'Rest Area',
    '37':'Restaurant',
    '38':'School/College',
    '39':'School-College/University',
    '40':'School-Elementary/Secondary',
    '41':'Service/Gas Station',
    '42':'Shelter-Mission/Homeless',
    '43':'Shopping Mall',
    '44':'Specialty Store',
    '45':'Tribal Lands',
    '98':'Other/Unknown',
    '99':'Not Specified',
}

crime_code = {
    '09A' : 1,
    '09B' : 2,
    '09C' : 3,
    '11A' : 4,
    '11B' : 5,
    '11C' : 6,
    '23A' : 7,
    '120' : 8,
    '13A' : 9,
    '220' : 10,
    '240' : 11,
    '23*' : 12,
    '13B' : 13,
    '13C' : 14,
    '100' : 15,
    '200' : 16,
    '210' : 17,
    '250' : 18,
    '26A' : 19,
    '26B' : 20,
    '26C' : 21,
    '26D' : 22,
    '26E' : 23,
    '26F' : 24,
    '26G' : 25,
    '270' : 26,
    '280' : 27,
    '290' : 28,
    '35A' : 29,
    '35B' : 30,    
    '36A' : 31,
    '36B' : 32,
    '370' : 33,
    '39A' : 34,
    '39B' : 35,
    '39C' : 36,
    '39D' : 37,
    '40A' : 38,
    '40B' : 39,
    '40C' : 40,    
    '510' : 41,
    '520' : 42,
    '64A' : 43,
    '64B' : 44,
    '58B' : 45,
    '58A' : 46,
    '61A' : 47,
    '61B' : 48,
    '49C' : 49,
    '26H' : 50,
    '620' : 51,
    '49B' : 52,
    '49A' : 53,
    '360' : 54,
    '526' : 55,
    '522' : 56,
    '521' : 57,
    '101' : 58,
    '103' : 59,
    '30A' : 60,
    '30B' : 61,
    '30C' : 62,
    '30D' : 63,
    '720' : 64,
    '90A' : 65,
    '90B' : 66,
    '90C' : 67,
    '90D' : 68,
    '90E' : 69,
    '90F' : 70,
    '90G' : 71,
    '90H' : 72,
    '90J' : 73,
    '90Z' : 74,
    '90K' : 75,
    '90L' : 76,
    '90M' : 77,
    '90I' : 78,
    '11D' : 79,
    '23B' : 80,
    '23C' : 81,
    '23D' : 82,
    '23E' : 83,
    '23F' : 84,
    '23G' : 85,
    '23H' : 86,
}