INSERT INTO public."State"("stateID", "stateName")VALUES 
	(1, 'Alaska'),
	(2,'Alabama'),
	(3, 'Arkansas'),
	(4, 'American Samoa'),
	(5, 'Arizona'),
	(6, 'California'),
	(7, 'Colorado'),
	(8, 'Connecticut'),
	(9, 'Canal Zone'),
	(10, 'District of Columbia'),
	(11, 'Delaware'),
	(12, 'Florida'),
	(13, 'Georgia'),
	(14, 'Guam'),
	(15, 'Hawaii'),
	(16, 'Iowa'),
	(17, 'Idaho'),
	(18, 'Illinois'),
	(19, 'Indiana'),
	(20, 'Kansas'),
	(21, 'Kentucky'),
	(22, 'Louisiana'),
	(23, 'Massachusetts'),
	(24, 'Maryland'),
	(25, 'Maine'),
	(26, 'Michigan'),
	(27, 'Minnesota'),
	(28, 'Missouri'),
	(29, 'Mississippi'),
	(30, 'Montana'),
	(31, 'Nebraska'),
	(32, 'North Carolina'),
	(33, 'North Dakota'),
	(34, 'New Hampshire'),
	(35, 'New Jersey'),
	(36, 'New Mexico'),
	(37, 'Nevada'),
	(38, 'New York'),
	(39, 'Ohio'),
	(40, 'Oklahoma'),
	(41, 'Oregon'),
	(42, 'Pennsylvania'),
	(43, 'Puerto Rico'),
	(44, 'Rhode Island'),
	(45, 'South Carolina'),
	(46, 'South Dakota'),
	(47, 'Tennessee'),
	(48, 'Texas'),
	(49, 'Utah'),
	(50, 'U.S. Virgin Islands'),
	(51, 'Virginia'),
	(52, 'Vermont'),
	(53, 'Washington'),
	(54, 'Wisconsin'),
	(55, 'West Virginia'),
	(56, 'Wyoming'),
	(57, 'Mariana Islands'),
	(98, 'Federal'),
	(99, 'Other');